### PR TITLE
Add errPropertyName option to log errors in the request finish messages

### PR DESCRIPTION
**Pull request by paroga**

### CODE REVIEW

**Comment by tellnes** [comment]
I'm not directly opposed to merging this, but I don't think this is the right approach. The request id this module adds to all the log messages lets you group the log messages together. If you instead uses multiple log messages by doing `req.log.error({ err })` it will also lett you have different log level for different log data for the same request.

**Comment by paroga** [comment]
I agree that it would be possible with a `req.log.err({err})`, but it makes analysis unnecessary complex, if you have only the possibility to filter the log messages (and can not combine them via the request id).
The error of an inexistent file might be ok for 404, but not for a 500. To show only errors which result in 500 status codes, you must be able to link the 500 request finish messages with the corresponding error message, but that requires more complex query capability in the log storage (which might is not available). Even in that scenario the request id makes perfekt sense, if you e.g. want to trace one request (which might have resulted in a 500 status code).
To be honest: I'm also not 100% in favour of this change, but I did not find a better solution, without changing my log storage. That might be a cleaner solution from a theoretical point of view, but is not very practical IMHO.

**Comment by tellnes** [comment]
What about an option to add properties to the `reqFinishData` object? Eg. a flag that says that all log messages for a given request should be grouped together.

**Comment by paroga** [comment]
ping?

**Comment by tellnes** [comment]
Hi. Github is not sending notification when the code is updated, so no notification before your ping message two days ago.

Since this I've been bit by an error which crashed the server after sending response headers but before the response was finished. That means if you are only logging on response finish, the log file would have no log message for the requested which crashed the server. Therefore I'm actually thinking on removing the feature to log only on response finish. I'm actually thinking of logging on more that the current two position (eg. on response headers sent).

Also, if the sockets unexpectedly closes before the response is finish, then you will loose this data in your logging.

To the question about linking the different log messages. What I'm doing is just `grep` with the request id on the log file. If you have a log infrastructure more special than that, then you probably have a search feature. Eg:
```
grep '0b689e38-5740-4705-b8c9-10d2a6c95275' my-app.log | bunyan
```

The only scenario I can see that you want to add addition log data to the response finish log is if you have data that is only interesting if the response successfully finishes and is never interesting if it does not. If you can give me an example where you want that I will reconsider, if not I think it is out of scope for this module.

**Comment by paroga** [comment]
ATM I personally want to log a catched error for e.g. a 500 response. But other scenarios could be to log the number of executed SQL statements during a request. For sure it would be possible to log that as additional log messages, but it makes filtering unnecessary complicated. When logging all that information in one log message i could easily filter with "if (statuscode == 500) print error". I do not want to check the log after everything is done. I want to do that live with a minimum on effort.

**Comment by tellnes** [comment]
Hmm

I do not like the current solution, so I will sleep on it and see if I can come up with a way to solve it while keeping it general and clean. But I might end up merging it.

**Comment by tellnes** [comment]
Merged as 5ae642da17abca2e678ca96b0b9f993a635f2d7c

**Comment by paroga** [comment]
thx!

**Pull request closed without merging**
