### PR TITLE
Updating deps.

### PR DESCRIPTION
**Pull request by evgeny-myasishchev**
Updating to the most recent node-uuid that fixes Math.random security warning.

### CODE REVIEW

**Comment by tellnes** [comment]
I'm not opposed to this, but why do you change the version range from `^` to `~`. Does not `node-uuid` follow semver? This change reduces the future version range to match again.

Also, `npm upgrade` or a fresh install with `npm install` should install that newest version.

**Comment by evgeny-myasishchev** [comment]
Hi @tellnes,

Changed back to ^ (was done by mistake). 

Sure npm upgrade/install will have the newest version. It's just that red message (dependencies:insecure) scares people like me when I have to chose one package over the other.

**Comment by tellnes** [comment]
Merged as e408e65c32f6ba78585a7f20ea1ad4381598a95f and published as v0.4.0. Thanks :)

**Comment by tellnes** [comment]
@evgeny-myasishchev Looks like you the email address you are using in your git commits is not associated with your Github user. I'll recommend that you adds it in your account settings. If not, you can always send a pull request with an [.mailmap](https://git-scm.com/docs/git-shortlog#_mapping_authors) file also.

**Pull request closed without merging**
